import { playSound } from './sound-manager.js';
const NS='http://www.w3.org/2000/svg',COLS=6,ROWS=11,TOTAL_BOXES=(COLS-1)*(ROWS-1),X0=14,Y0=16,DX=14.4,DY=14.8;
let svg,cards,message,players=[],active=0,selected=null,locked=false,finished=false,onComplete=null,edges=new Set(),boxes=new Map(),groups={};
const reduced=()=>matchMedia('(prefers-reduced-motion: reduce)').matches;
const point=(id)=>({c:id%COLS,r:Math.floor(id/COLS),x:X0+(id%COLS)*DX,y:Y0+Math.floor(id/COLS)*DY});
const key=(a,b)=>a<b?`${a}-${b}`:`${b}-${a}`;
const adjacent=(a,b)=>{const p=point(a),q=point(b);return Math.abs(p.c-q.c)+Math.abs(p.r-q.r)===1};
const usable=(a,b)=>adjacent(a,b)&&!edges.has(key(a,b));
const el=(tag,attrs={})=>{const node=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>node.setAttribute(k,v));return node};
const availableFrom=(id)=>Array.from({length:COLS*ROWS},(_,i)=>i).filter(i=>usable(id,i));
function validTargets(){return selected===null?[]:availableFrom(selected)}
function paintSelection(){svg.style.setProperty('--player',players[active].color);const targets=validTargets();svg.querySelectorAll('.dot').forEach((dot,i)=>{dot.classList.toggle('selected',i===selected);dot.classList.toggle('valid',targets.includes(i))})}
function announce(text){message.textContent=text}
function renderCards(){cards.innerHTML='';players.forEach((p,i)=>{const card=document.createElement('article');card.className=`player-card${i===active&&!finished?' active':''}`;card.style.setProperty('--player',p.color);card.innerHTML=`<span class="player-avatar" aria-hidden="true">${p.avatar}</span><span class="player-name"></span><span class="player-score">${p.boxes} box${p.boxes===1?'':'es'}</span>`;card.querySelector('.player-name').textContent=p.name;cards.append(card)})}
function boxEdges(c,r){const tl=r*COLS+c,tr=tl+1,bl=tl+COLS,br=bl+1;return[key(tl,tr),key(bl,br),key(tl,bl),key(tr,br)]}
function completedBy(edgeKey){const [a,b]=edgeKey.split('-').map(Number),p=point(a),q=point(b),candidates=[];if(p.r===q.r){const c=Math.min(p.c,q.c);if(p.r>0)candidates.push([c,p.r-1]);if(p.r<ROWS-1)candidates.push([c,p.r])}else{const r=Math.min(p.r,q.r);if(p.c>0)candidates.push([p.c-1,r]);if(p.c<COLS-1)candidates.push([p.c,r])}return candidates.filter(([c,r])=>!boxes.has(`${c}-${r}`)&&boxEdges(c,r).every(e=>edges.has(e)))}
function claim(c,r){boxes.set(`${c}-${r}`,active);const rect=el('rect',{x:X0+c*DX+.9,y:Y0+r*DY+.9,width:DX-1.8,height:DY-1.8,rx:2,class:'box-claim'});rect.style.setProperty('--player',players[active].color);groups.boxes.append(rect)}
async function commit(a,b){locked=true;selected=null;paintSelection();const p=point(a),q=point(b),line=el('line',{x1:p.x,y1:p.y,x2:q.x,y2:q.y,pathLength:1,class:'edge temp'});line.style.setProperty('--player',players[active].color);groups.lines.append(line);playSound('linedraw');await new Promise(resolve=>setTimeout(resolve,reduced()?0:300));line.classList.remove('temp');edges.add(key(a,b));const won=completedBy(key(a,b));won.forEach(([c,r])=>claim(c,r));if(won.length){players[active].boxes+=won.length;playSound('boxclaim');announce(`${players[active].name} claimed ${won.length===2?'two boxes':'a box'} and plays again.`)}else{active=(active+1)%players.length;announce(`${players[active].name}'s turn. Choose a dot.`)}if(boxes.size===TOTAL_BOXES){finished=true;const highest=Math.max(...players.map(player=>player.boxes)),winners=players.filter(player=>player.boxes===highest);announce(winners.length===1?`${winners[0].name} wins with ${highest} boxes!`:`${winners.map(player=>player.name).join(' and ')} tie with ${highest} boxes!`);renderCards();paintSelection();setTimeout(()=>onComplete?.({players:players.map(player=>({...player})),winners:winners.map(player=>({...player}))}),reduced()?0:450);return}renderCards();paintSelection();locked=false}
function choose(id){if(locked||finished)return;if(selected===null){if(!availableFrom(id).length){playSound('error');announce('No available line from this dot.');return}playSound('tap');selected=id;announce('Now choose a glowing adjacent dot.');paintSelection();return}if(id===selected){playSound('tap');selected=null;announce(`${players[active].name}'s turn. Choose a dot.`);paintSelection();return}if(usable(selected,id)){const start=selected;commit(start,id);return}if(!availableFrom(id).length){playSound('error');announce('No available line from this dot. Choose a glowing dot or another starting dot.');return}playSound('tap');selected=id;announce('Start moved. Choose a glowing adjacent dot.');paintSelection()}
function build(){svg.replaceChildren();const defs=el('defs');defs.innerHTML='<radialGradient id="dot-gradient" cx="35%" cy="25%"><stop offset="0" stop-color="#fff"/><stop offset=".35" stop-color="#cbd5e1"/><stop offset="1" stop-color="#526579"/></radialGradient>';svg.append(defs);groups.boxes=el('g');groups.lines=el('g');groups.dots=el('g');groups.hits=el('g');svg.append(groups.boxes,groups.lines,groups.dots,groups.hits);for(let i=0;i<COLS*ROWS;i++){const p=point(i),dot=el('circle',{cx:p.x,cy:p.y,r:2.55,class:'dot'}),hit=el('circle',{cx:p.x,cy:p.y,r:6.2,class:'hit-target',tabindex:0,role:'button','aria-label':`Dot row ${p.r+1}, column ${p.c+1}`});hit.addEventListener('click',()=>choose(i));hit.addEventListener('focus',()=>dot.classList.add('keyboard-focus'));hit.addEventListener('blur',()=>dot.classList.remove('keyboard-focus'));hit.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();choose(i)}});groups.dots.append(dot);groups.hits.append(hit)}}
export function initializeBoard(options={}){svg=document.getElementById('dots-board');cards=document.getElementById('player-cards');message=document.getElementById('game-message');players=(options.players||[]).map(player=>({...player,boxes:0}));onComplete=typeof options.onComplete==='function'?options.onComplete:null;active=0;selected=null;locked=false;finished=false;edges=new Set();boxes=new Map();build();renderCards();paintSelection();announce(`${players[active].name}'s turn. Choose a dot.`)}
