import QRCode from 'qrcode';
import { initializeBoard } from './board-ui.js';
import { showScreen, showToast } from './platform-ui.js';
const avatars=['🦊','🐼','🐸','🦁','🐙','🦄'];
const colors=[['Ocean','#2563eb'],['Berry','#db2777'],['Leaf','#16a34a'],['Sun','#eab308'],['Grape','#7c3aed'],['Coral','#ea580c']];
let players=[],isHost=false,roomCode='DOTS66';
function buildPickers(){document.querySelectorAll('.avatar-picker').forEach(p=>avatars.forEach((avatar,i)=>{const b=document.createElement('button');b.type='button';b.className='pick';b.dataset.value=avatar;b.setAttribute('aria-label',avatar);b.setAttribute('aria-pressed',String(i===0));b.textContent=avatar;p.append(b)}));document.querySelectorAll('.color-picker').forEach(p=>colors.forEach(([name,color],i)=>{const b=document.createElement('button');b.type='button';b.className='pick color-pick';b.dataset.value=color;b.style.setProperty('--pick-color',color);b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String(i===0));p.append(b)}));document.querySelectorAll('.picker').forEach(p=>p.addEventListener('click',e=>{const b=e.target.closest('.pick');if(!b)return;p.querySelectorAll('.pick').forEach(x=>x.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true')}))}
const picked=(name)=>document.querySelector(`[data-picker="${name}"] .pick[aria-pressed="true"]`)?.dataset.value;
function mockPlayers(name,avatar,color,hostSelected){const used=new Set([color]);const rest=colors.map(x=>x[1]).filter(c=>!used.has(c));const selected={name,avatar,color,boxes:0};const mocks=[{name:'Maya',avatar:'🐼',color:rest[0]},{name:'Leo',avatar:'🦁',color:rest[1]},{name:'Nova',avatar:'🦄',color:rest[2]}];return hostSelected?[selected,...mocks]:[mocks[0],selected,mocks[1],mocks[2]]}
function enterLobby(name,avatar,color,host){/* Visual-prototype only: room membership is local mock data until Firebase is introduced. */isHost=host;players=mockPlayers(name,avatar,color,host);document.getElementById('lobby-code').textContent=roomCode;const list=document.getElementById('lobby-players');list.innerHTML='';players.forEach((p,i)=>{const li=document.createElement('li');li.style.setProperty('--player',p.color);li.innerHTML='<span class="player-swatch"></span><span class="avatar"></span><span class="name"></span>';li.querySelector('.avatar').textContent=p.avatar;li.querySelector('.name').textContent=p.name;if(i===0){const badge=document.createElement('span');badge.className='host-badge';badge.textContent='HOST';li.append(badge)}list.append(li)});showScreen('lobby')}
function startGame(){showScreen('gameplay');document.getElementById('end-game').hidden=!isHost;initializeBoard({players})}
function validName(id){const value=document.getElementById(id).value.trim();if(!value)showToast('Please enter your name.');return value}
function wire(){document.getElementById('home-host').onclick=()=>showScreen('create-room');document.getElementById('home-join').onclick=()=>showScreen('join-room');document.querySelectorAll('[data-home]').forEach(b=>b.onclick=()=>showScreen('home'));document.getElementById('create-submit').onclick=()=>{const name=validName('create-name');if(name)enterLobby(name,picked('create-avatar'),picked('create-color'),true)};document.getElementById('join-submit').onclick=()=>{const code=document.getElementById('join-code').value.trim().toUpperCase(),name=validName('join-name');if(!/^[A-Z0-9]{4,6}$/.test(code)){showToast('Enter a 4–6 character room code.');return}if(name){roomCode=code;enterLobby(name,picked('join-avatar'),picked('join-color'),false)}};document.getElementById('start-game').onclick=startGame;document.getElementById('leave-lobby').onclick=()=>showScreen('home');document.getElementById('play-again').onclick=startGame;document.getElementById('end-game').onclick=()=>{if(confirm('End this game and return home?'))showScreen('home')};wireShare();wireMute()}
function wireShare(){document.getElementById('share-code').onclick=async()=>{const text=`Join my Dots & Boxes room: ${roomCode}`;try{if(navigator.share)await navigator.share({title:'Dots & Boxes',text,url:location.href});else{await navigator.clipboard.writeText(`${text} ${location.href}`);showToast('Room details copied.')}}catch(e){if(e.name!=='AbortError')showToast('Could not share room.')}};document.getElementById('show-qr').onclick=async()=>{document.getElementById('qr-image').src=await QRCode.toDataURL(`${location.origin}${location.pathname}?room=${encodeURIComponent(roomCode)}`,{width:240,margin:1});document.getElementById('qr-dialog').showModal()};document.getElementById('close-qr').onclick=()=>document.getElementById('qr-dialog').close()}
function wireMute(){const input=document.getElementById('mute'),icon=document.getElementById('mute-icon');input.checked=localStorage.getItem('dots-muted')==='true';const sync=()=>{icon.textContent=input.checked?'🔇':'🔊';localStorage.setItem('dots-muted',String(input.checked))};input.onchange=sync;sync()}
function registerServiceWorker(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('/sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const worker=reg.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller){showToast('Update ready — refresh to apply.',4000)}})})}).catch(()=>{})}
buildPickers();wire();if(new URLSearchParams(location.search).get('preview')==='gameplay'){/* Visual-prototype direct preview uses deterministic local players. */isHost=true;players=mockPlayers('You','🦊','#2563eb',true);startGame()}else showScreen('home');registerServiceWorker();
